apiVersion: node.eks.aws/v1alpha1
kind: NodeConfig
spec:
  cluster:
    name: hybrid # Name of the EKS cluster
    region: us-west-2 # AWS Region where the EKS cluster resides
    # Use the public EKS API server endpoint
    # endpoint: https://10EAC79EAF8CB890A26699ACD31D6EA5.gr7.us-west-2.eks.amazonaws.com
  kubelet:
    flags:
      - --fail-swap-on=false
      - --cloud-provider=external
      - --node-ip=192.168.7.217 # May not be necessary depending on your network setup
      - --v=5
    config:

  containerd:
    config: |
      [plugins."io.containerd.grpc.v1.cri"]
        sandbox_image = "registry.k8s.io/pause:3.9"

      [plugins."io.containerd.grpc.v1.cri".registry]
        config_path = "/etc/containerd/certs.d:/etc/docker/certs.d"
  hybrid:
    ssm:
      activationCode: xxxx # SSM hybrid activation code
      activationId: xxxx # SSM hybrid activation id
